### ISSUE TITLE
fuse can create a different rendered results when used with annotations

### ISSUE THREAD

**Issue by 1Jajen1** [quchen/prettyprinter#108]
First of all, thank you for writing/maintaning this awesome library, I've really enjoyed using it for my haskell projects :). Since I also do quite a bit of kotlin + arrow-kt, and I needed a prettyprinter there, I decided to port this over, which went surprisingly smooth (given the stacksafety and performance concerns I had). 
After writing some tests for `fuse` I noticed that the test fails when it contains annotated empty documents. Those may still contain valid information for rendering, but `fuse` removes them entirely.

https://github.com/quchen/prettyprinter/blob/cce40981ec6e8b2605e5eefcef85cab870fc0ac6/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs#L1404
This line should be the culprit. It should probably just recursively `fuse` the inner part.

**Comment by sjakobi** [comment]
Thanks for the report!

Could you possibly make a reproducer that would demonstrate the issue?

The code you linked looks to me like the annotation removal is intentional, so I'm wondering what the thought process behind that was. The line was introduced in https://github.com/quchen/prettyprinter/commit/d0d410a36e3b924d621b386985a28f6c21ddbfbd#diff-a5f4db1861ac35bad3e3235e67dd94eaR1393 but there's no context that would explain it.

Could you also help me understand how an annotation on an empty chunk would be used? I've only recently become involved in the maintenance of this project, and my experience with annotations is limited to terminal colours, where such an annotation would be useless.

Lastly, could you share your tests for `fuse`? The existing property test failed to catch the issue since it relies on `renderStrict`, which ignores annotations:

https://github.com/quchen/prettyprinter/blob/677ca47bf75dfc6c8f66fb6e2854ae846cc14e8a/prettyprinter/test/Testsuite/Main.hs#L86-L101

**Comment by 1Jajen1** [comment]
Could you possibly make a reproducer that would demonstrate the issue?

Sure:
```haskell
test :: Doc String
test = annotate "<Hello>" mempty

renderTest :: Doc String -> String
renderTest = renderSimplyDecorated T.unpack id id . layoutPretty defaultLayoutOptions

renderTestFused :: Doc String -> String
renderTestFused = renderSimplyDecorated T.unpack id id . layoutPretty defaultLayoutOptions . fuse Deep
```

> Could you also help me understand how an annotation on an empty chunk would be used? I've only recently become involved in the maintenance of this project, and my experience with annotations is limited to terminal colours, where such an annotation would be useless.

You are not wrong, I can't really think of good usecases as well ^^. Stuff image src (images to append for example), icons (although those are better as annotations over chars because of width) etc. These are not good usecases and there are probably better ways to do them ^^
There is one use-case that is probably terrible but valid imo: ansi codes like clear page, stepping back and forth etc.

> Lastly, could you share your tests for fuse? The existing property test failed to catch the issue since it relies on renderStrict, which ignores annotations:

Sure, it's quite the cheap method: (also don't mind the noisy kotlin code^^) https://github.com/1Jajen1/kotlin-pretty/blob/50f05309db704094e82f8814f161f75e576d1bee/kotlin-pretty/src/test/kotlin/pretty/DocTest.kt#L48-L66

Basic idea is just to wrap annotations (to see what happens when the annotation is "" as shrinkers like to produce) and simply render them as string.

**Comment by sjakobi** [comment]
Thanks for the reproducer! :)

Looks like we could change `fusionDoesNotChangeRendering` to use `StackMachine.renderSimplyDecorated` to check that annotations are preserved. (We'd probably also have to change the generator to produce annotations.)


> https://github.com/quchen/prettyprinter/blob/cce40981ec6e8b2605e5eefcef85cab870fc0ac6/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs#L1404
> 
> 
> This line should be the culprit. It should probably just recursively `fuse` the inner part.

It's actually interesting that `fuse` doesn't recurse into `Annotated`s. I wonder whether there's some reasoning similar to the one regarding `removeTrailingWhitespace` at play:

https://github.com/quchen/prettyprinter/blob/cce40981ec6e8b2605e5eefcef85cab870fc0ac6/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs#L1456-L1460

Although, in the case of `fuse`, I don't see what it could break…

@quchen Could you possibly clarify why `fuse` handles `Annotated`s in this way?

**Comment by quchen** [comment]
I can’t think of a reason better than »it’s an oversight«. `Doc` is not supposed to be inspectable by the library consumer, so `Cat "hello" "world"` should render like `"helloworld"`, annotated or not.

**Comment by sjakobi** [comment]
Let's change `fuse` then to recurse into `Annotated`s and lets also test that annotations are preserved.

@1Jajen1 Would you be interested in making a PR?
