### ISSUE TITLE
Add the simple stack machine display functions from other annotated prettyprinters

### ISSUE THREAD

**Issue by quchen** [quchen/prettyprinter#13]
This is a simpler kind of stack machine based rendering, when all we’re concerned about is printing output, pushing and popping based on certain SimpleDoc constructors. This won’t allow fancy stack machines that peek, double-push and what not.

e.g. [annotated-wl-pprint contains:](http://hackage.haskell.org/package/annotated-wl-pprint-0.7.0/docs/src/Text-PrettyPrint-Annotated-Leijen.html#displayDecoratedA)
```haskell
displayDecoratedA :: (Applicative f, Monoid b)
                  => (String -> f b) -> (a -> f b) -> (a -> f b)
                  -> SimpleDoc a -> f b
displayDecoratedA str start end sd = display [] sd
  where display []        SEmpty              = pure mempty
        display stk       (SChar c x)         = (str [c]) <++> (display stk x)
        display stk       (SText l s x)       = (str s) <++> (display stk x)
        display stk       (SLine ind x)       = (str ('\n':indentation ind)) <++> (display stk x)
        display stk       (SAnnotStart ann x) = (start ann) <++> (display (ann:stk) x)
        display (ann:stk) (SAnnotStop x)      = (end ann) <++> (display stk x)

        -- malformed documents
        display []        (SAnnotStop _)      = error "stack underflow"
        display stk       SEmpty              = error "stack not consumed by rendering"

        (<++>) = liftA2 mappend
```

Convinced this is a good idea in #12.

**Comment by minad** [comment]
where do you need double push and the additional power? just out of interest...

**Comment by quchen** [comment]
Rendering to ANSI terminal directly, for example. When removing a style, you need to pop the current one, and then peek what the previous one was, in order to set the new one correctly.
