### ISSUE TITLE
Derive Functor for Doc, SimpleDoc, SimpleDocTree

### ISSUE THREAD

**Issue by minad** [quchen/prettyprinter#14]
If you want to keep the name I would suggest to make reAnnotate an fmap alias with specific type for Doc, SimpleDoc and SimpleDocTree

**Comment by quchen** [comment]
The question is where does this help the user. I’ve seen confusing uses of `fmap` when it meant reannotation, but I haven’t seen a Functor-generic function that makes good use of `Doc` having an instance.

**Comment by minad** [comment]
Sure it helps since it gives the datatype structure that users can rely on, even if they don't use the generic functions directly. Especially here it is useful since the functor is unique and guarantees that the structure is not altered via fmap id = id!

I see it like this - you start with a structureless datatype and via lawful typeclass the datatype acquires some algebraic structure. Therefore such instances should be provided as long as there is no reason to hide the structure.

You could also provide Traversable and Foldable btw. For Foldable, the law argument wouldn't count, but I can imagine use cases where one would want to extract all annotations from a Doc.

**Comment by minad** [comment]
What abou Foldable, Traversable etc? Traversable could be useful if you reannotate but need access to effects, e.g. state.

**Comment by minad** [comment]
I feel like nitpicking a lot. Please let me know if I should either implement PRs or if the direction you want this to develop seems to divergent from my opinions. Thanks!

**Comment by quchen** [comment]
It's a slippery slope to cluttering the docs when adding all the possible instances ;-) I'm having a hard time imagining when an Applicative annotation might be useful (for use with Traversable).

**Comment by minad** [comment]
I've never seen the documentation as a problem. As I already argued I see the presence of instances as guarantees and documentation. I thought it is better if libraries just provide the standard instances if possible to avoid orphan instances.

You could also wait until someone comes up with a use case and then you add the instance if requested ;)

**Comment by quchen** [comment]
I guess since I'm also usually in the "have all correct instances" camp I'm running out of arguments here. ;-)
