### ISSUE TITLE
SimpleDocTree via SimpleDoc

### ISSUE THREAD

**Issue by minad** [quchen/prettyprinter#15]
Some other question that came up while I was reviewing your code. Why do you go via SimpleDoc for SimpleDocTree?

Would it not be possible to have the following two paths?
~~~ haskell
Doc -> StreamDoc -> TextLike
Doc -> TreeDoc -> HtmlLike
~~~

**Comment by minad** [comment]
I would also prefer the names compared to SimpleDoc which doesn't have much meaning.

**Comment by quchen** [comment]
The layout algorithm is fairly straightforward from Doc to SimpleDoc; I don’t see this for SimpleDocTree. I thought about this and couldn’t come up with a solution that duplicates the renderer’s code.

**Comment by quchen** [comment]
I renamed `SimpleDoc` to `SimpleDocStream` in c78d145f3d68dd59c9fab2ad13b9d21fc6f837e2. As for going from `Doc` to `SimpleDocTree` directly, that’s just function composition. I’m open to an optimized direct route though.

**Comment by minad** [comment]
ok cool! The Simple you want to keep though it seems ;)

**Comment by quchen** [comment]
For the lack of a better name, yes. It would be better if `Doc` was called `RichDoc`, but that would clutter the definitions too much and probably not help the average user.
