### ISSUE TITLE
Add a dieDoc function

### ISSUE THREAD

**Issue by ad-si** [quchen/prettyprinter#161]
I'm not entirely sure I fully understand how the rendering pipeline works so maybe this is ill advised, but wouldn't it make sense to have a `dieDoc` function?
It returns non zero exit code and prints the `Doc` to `stderr` just like `putDoc`.

**Comment by sjakobi** [comment]
Hm, I don't feel that the libraries here should get into the business of exit codes.

If we remove that from your request, we're left with something like

    putDocStderr :: Doc {ann,AnsiStyle} -> IO ()

But any user can define that very easily as

    hPutDoc System.IO.stderr

…so I'm not yet convinced it's worth adding…

---

Do you have any questions regarding the rendering pipeline though, or suggestions on how to improve the documentation?

**Comment by ad-si** [comment]
What I'm looking for is to short circuit all further execution and just print the error message. Without a `dieDoc` I have to either thread an `Either` through the whole program, or `throw` and `catch` errors. Which both seems to much hassle if all I really want is to immediately exit and pretty print the error…

> Do you have any questions regarding the rendering pipeline though, or suggestions on how to improve the documentation?

Thanks, but I meant it more like "I haven't read the documentation as carefully as I should have 😅". Otherwise it looks really extensive 👏

**Comment by ad-si** [comment]
Ok well, actually I can do `hPutDoc stderr filterHelp >> exitFailure`.
Then I guess there is no real need to simplify this even further…
