### ISSUE TITLE
PRs don't show Travis build status

### ISSUE THREAD

**Issue by sjakobi** [quchen/prettyprinter#172]
Many recent PRs didn't show their Travis build status. This is a bit annoying.

I've been experiencing the same thing in other projects for a few months now. I don't have much hope that it will get better by itself.

**Comment by sjakobi** [comment]
I've finally managed to get this fixed for my personal `bsb-http-chunked` project. See e.g. [this PR](https://github.com/sjakobi/bsb-http-chunked/pull/35).

@quchen I think you need to do the following:

* At https://travis-ci.com/account/migrate subscribe to the "beta" at the bottom of the page

* Select `prettyprinter` for migration to travis-ci.com.

**Comment by quchen** [comment]
Okay, it’s migrated. Is using `.com` intentional? I thought this was the corporate branch of the open-source `.org` Travis.

**Comment by sjakobi** [comment]
> Okay, it’s migrated.

Awesome! It works! Just yesterday we had more trouble with the migration of `checkers` so we ended up moving it to a new GitHub organization.


> Is using `.com` intentional? I thought this was the corporate branch of the open-source `.org` Travis.

It's intentional, but I don't really understand why this seems to be the best way to fix the issue. My understanding is that with the introduction of GitHub CI, the integration of travis-ci.org became less reliable. I've heard of rate limiting, although that shouldn't have posed a problem for this repo.
