### ISSUE TITLE
Haddockumentation on Hackage shows old module hierarchy

### ISSUE THREAD

**Issue by andreasabel** [quchen/prettyprinter#192]
https://hackage.haskell.org/package/prettyprinter shows Data/Text/Prettyprint/... only still.  These modules link to deprecated stubs.
Ok, from there you get to the real modules, but there is no display of the new module tree (at least not in-your-face).

**Comment by sjakobi** [comment]
I'm seeing the `Prettyprinter` module hierarchy below the old `Data.Text.Prettyprinter` hierarchy. Did you possibly look at an old version of `prettyprinter`?

As long as the old hierarchy exists, I'd prefer showing it in the haddocks too – otherwise people who encounter these modules in a code base might be confused.

**Comment by sjakobi** [comment]
![image](https://user-images.githubusercontent.com/3664523/107222415-2dc9f600-6a15-11eb-8839-325f13f47dc1.png)

**Comment by andreasabel** [comment]
Weird.  I could swear I didn't see anything below the Data.Text hierarchy.  But well, _appearances can be deceiving_, as Agent Smith said.
Sorry for the spam.

**Comment by sjakobi** [comment]
No worries! :)

**Comment by andreasabel** [comment]
I saw the unicorn again today: 
<img width="1130" alt="Screenshot 2021-02-22 at 17 23 40" src="https://user-images.githubusercontent.com/1155218/108774488-03715000-7560-11eb-975f-4954a6349ce5.png">

Ah, but now I understand.  It is just the rendering in a not-super-wide window.  The rest follows after a page length of a blank lhs, until the rhs info is finished.  The name 'Data.Text.Prettyprint.Doc.Render.Tutorials.StackMachineTutorial' is just too long, maybe this was the reason for renaming...

**Comment by sjakobi** [comment]
Oh! I can reproduce this in Firefox too. Not with Chromium though.  Maybe this could be fixed by adjusting the relevant CSS…

**Comment by andreasabel** [comment]
Yeah, there would be plenty of horizontal space if the left and right margin wouldn't be so excessive...
