### ISSUE TITLE
Benchmarks are run with threaded runtime and +RTS -N

### ISSUE THREAD

**Issue by Bodigrim** [quchen/prettyprinter#197]
`prettyprinter` configures all benchmarks with 
https://github.com/quchen/prettyprinter/blob/11e8bf12aed2f698e619c3a8c07eca3af4da1aed/prettyprinter/prettyprinter.cabal#L202
What's the reason for this? (I suspect a copy-paste from test suites?..)

I mean, it does not make sense to run benchmarks concurrently, because results would be wildly wrong. So neither `criterion` nor `gauge` nor `tasty-bench` do it. The only effect of such configuration is parallel GC over all cores, which in my experience (especially with otherwise default RTS parameters) negatively affects relevance of performance metrics.

**Comment by quchen** [comment]
This is indeed a copy+paste issue. Looks like it’s alredy fixed in @sjakobi’s branch.

**Comment by sjakobi** [comment]
Thanks for the report @Bodigrim! :)

I've opened https://github.com/quchen/prettyprinter/pull/199 with the fix.
