### ISSUE TITLE
Squashing consecutive newlines

### ISSUE THREAD

**Issue by newhoggy** [quchen/prettyprinter#201]
Is it possible to add a special kind of newline whereby if there were more than one consecutive such newline they will be squashed into one?

**Comment by newhoggy** [comment]
Similarly for spaces.

**Comment by quchen** [comment]
This has been requested multiple times via various channels, and I’m not a fan of it.

# Code

On a code level, it would be quite complicated, and thus only pitfall-heavy. For example: what do we do with `collapseLine <> ann "test" collapseLine`?

# Usage

- To how many lines do we collapse – maybe we want to keep a single empty line max, thus should it be `collapseToMaxEmptyLines 1`?
- Can we somehow cancel a previously set collapse-linebreak if e.g. a previous producer has one but we’d like to have a hard line break?
- What’s the semantics of `line <> collapseLine`, `collapseLine <> line`?

# My recommendation

Produce your documents with `concatWith`, and insert the desired amount of lines between manually. Don’t use the layouter to clean up your `Doc`, but rather create it in a way it doesn’t have to.

**Comment by newhoggy** [comment]
Thanks for you advice and suggestions!
