### ISSUE TITLE
Missing build-dependency constraints

### ISSUE THREAD

**Issue by glguy** [quchen/prettyprinter#21]
The package looks interesting, but the lack of constraints in the build-depends suggests that it's a throw away package. I'd be great if you were planning on maintaining this at all if you could reflect what versions of things it works with in the build-depends.

**Comment by quchen** [comment]
> suggests that it's a throw away package

Miles of documentation and tests »suggest« that it’s not. I’ll add some best guesses for the dependencies as soon as possible.

**Comment by quchen** [comment]
Done https://github.com/quchen/prettyprinter/commit/2162035f47eb5fa4b4a7317db2cea0ceab5108b8

Backporting it to the 1.0 Hackage release as well.
