### ISSUE TITLE
Incorrect usage of MINIMAL pragma?

### ISSUE THREAD

**Issue by dwincort** [quchen/prettyprinter#218]
I'm not sure why there's a `MINIMAL` pragma for the `Pretty` class considering that there's a default implementation for `pretty`.  This seems a lot like [a similar issue with `toJSON` in `aeson`](https://gitlab.haskell.org/ghc/ghc/-/issues/10959), and the solution looks like the pragma shouldn't be there.

**Comment by sjakobi** [comment]
Yes, let's remove the pragma.
