### ISSUE TITLE
group always constructs Union, resulting in unnecessary work

### ISSUE THREAD

**Issue by nwf** [quchen/prettyprinter#22]
Even when it's not necessary to do so.  See https://github.com/ekmett/wl-pprint-extras/issues/16 for the bug report against (yet another) pretty-printer library and my proposed fix, which modifies flatten to reveal when it (might have) had an effect.

**Comment by quchen** [comment]
Interesting! The fact that the renderer is exponential in the worst case is not surprising, but I agree that it’s undesirable.

For testing purposes, here is the code that takes a long time to run from the other ticket:

```haskell
main = putDoc $ iterate ( \ hole ->  hsep [hole, sep []] ) (text  "l") !! 100
```

**Comment by quchen** [comment]
Fixed, thanks! The example now renders with n = 1000, so I think this performance hog is solved.
