### ISSUE TITLE
Confusion about how an HTML backend should be implemented

### ISSUE THREAD

**Issue by mitchellwrosen** [quchen/prettyprinter#238]
Hi all,

The README claims an HTML backend is trivial to implement:

![Screenshot from 2023-04-05 11-07-42](https://user-images.githubusercontent.com/1074598/230123687-8c518ceb-0302-44a3-9101-ee73b8ee4218.png)

And the main library documentation suggests you might start the conversion from a `SimpleDocTree`:

![Screenshot from 2023-04-05 11-08-30](https://user-images.githubusercontent.com/1074598/230123926-f51243a2-f0be-4041-b8e4-c3f987f93677.png)

However, the `SimpleDocTree` documentation suggests it's not suitable for rendering to HTML:

![Screenshot from 2023-04-05 11-09-30](https://user-images.githubusercontent.com/1074598/230124144-b6f54287-ac0b-4f3b-a303-6f6d3768a395.png)

Perhaps the diagram in the second screenshot is a bit out of date? Thanks!

**Comment by Lev135** [comment]
> However, the SimpleDocTree documentation suggests it's not suitable for rendering to HTML

It seems that you misread the documentation here just said that `SimpleDocStream` is not suitable for rendering HTML and you should use `SimpleDocTree`.

**Comment by georgefst** [comment]
For what it's worth, I have actually implemented [an HTML backend](https://hackage.haskell.org/package/prettyprinter-lucid), though I haven't actually used it extensively or recently.

**Comment by mitchellwrosen** [comment]
@Lev135 Ah, thanks! Yes, I did misread the docs. It's confusing for the reader to begin the documentation for `SimpleDocTree` with "A `SimpleDocStream` ..." :sweat_smile:
