### ISSUE TITLE
Allow multiple formatting modes in a single AnsiTerminal value

### ISSUE THREAD

**Issue by glguy** [quchen/prettyprinter#25]
It might be nice if a single `AnsiTerminal` value could fully describe all the possible formatting options in a single value. This would allow me to store set of these in a single record as a palette for formatting `Doc` values.

Additionally this would allow me to use `reAnnotate` to annotate a Doc with formatting that is more interesting than only applying a single effect like `Bold` or a single color.

For a similar example, see the `vty` package's `Attr` type http://hackage.haskell.org/package/vty-5.15.1/docs/Graphics-Vty-Attributes.html#t:Attr

Here's an example of what I'm trying to do. I have a `Doc Ann` value where `data Ann = Key | Atom | Required | Description | Primitive`

Next I'd like to write a function `palette :: Ann -> AnsiTerminal`. Currently I can only set one `AnsiMode` when I do this. Whether or not allowing `Bold` _and_ `Underlined` is going to look good, this should probably be possible.

![screen shot 2017-06-04 at 2 20 58 pm](https://cloud.githubusercontent.com/assets/12164/26765456/1c5036a4-4931-11e7-8034-91cb67363134.png)

Possible alternative (names and types certainly revisable):

```haskell
data AnsiTerminal = AnsiTerminal
  { bold, underlined, italicized :: Bool
  , foreground, background :: Maybe (Intensity, Color)
  }
```

It might be better to use a three-way type instead of `Bool` and `Maybe` allowing for `Set`, `Clear`, and `Ignore` so that bold could be turned on, off, or left alone.

**Comment by quchen** [comment]
Unifying the styles is possible to do, and actually done by the library behind the curtains [(see the `CombinedStyle` type)](https://github.com/quchen/prettyprinter/blob/f7a91907224e2b2d187724aa91711ab78361f3e1/prettyprinter-ansi-terminal/src/Data/Text/Prettyprint/Doc/Render/Terminal.hs#L176). I agree that it might indeed make a nicer, or if not that than more uniform, API. I wonder whether the breakage is worth it.

5 minutes after publishing the last version, I realized that `alterAnnotations` should have an argument `ann -> [ann']`, allowing one annotation to become multiple, instad of just one (`ann -> Maybe ann'`). With this, you can also solve your problem even without changing the ANSI types, by e.g. mapping `Keyword` to `[Bold, Green]`. Introduced in b653d592a337fa083859f79b0d893174a2d805a5

**Comment by glguy** [comment]
The AnsiTerminal type was only exposed today, so there shouldn't be much breakage cause by fixing it.

**Comment by quchen** [comment]
@glguy Mind reviewing the change? I’ve also updated the online docs, which is maybe more readable at first glance: https://quchen.github.io/ansi-wl-pprint-docdump/prettyprinter-ansi-terminal-1.1/Data-Text-Prettyprint-Doc-Render-Terminal.html
