### ISSUE TITLE
Add printf support

### ISSUE THREAD

**Issue by quchen** [quchen/prettyprinter#33]
`Text.Printf` would be a nice addition to the `prettyprinter` toolbox. The documentation makes it look fairly simple to implement this: https://hackage.haskell.org/package/base-4.9.1.0/docs/Text-Printf.html#g:2

**Comment by quchen** [comment]
Nevermind – printf allows arguments to be extended to new types, but not results. In other words, we can’t implmenent `printf :: … -> Doc ann`. :-(

**Comment by bezirg** [comment]
Hello, 

adding this wouldn't help?

``` instance PrintfArg (Doc ann) where
   formatArg  = formatString . show  --- or some renderString
```

It helped me remove some redundant render calls when I am prettyprinting and combining with text printf's "string interpolation".

Example code:

```
instance PrintfArg (Doc ann) where
   formatArg  = formatString . show  --- or some renderStringghci>printf "%d%s" 3 (pretty 3)
33it :: ()
ghci>printf "%s%s" 3 (pretty 3)
*** Exception: printf: bad formatting char 's'
ghci>printf "%d%d" 3 (pretty 3)
3*** Exception: printf: bad formatting char 'd'
```
