### ISSUE TITLE
Consider a larger default ribbon width

### ISSUE THREAD

**Issue by joelburget** [quchen/prettyprinter#37]
I was confused for a while why my pretty-printing only ever took < 40 chars, until I realized the culprit is the `defaultLayoutOptions` ribbon width of 0.4. I think 1 is what I expected.

**Comment by quchen** [comment]
0.4 was the original default, which I did not question. I'm open to changing it to a different number. 1 seems sensible; question is where the consensus is.

**Comment by quchen** [comment]
Done. I wasn’t sure whether this was an improvement since 0.4 has been a default for ages, but 1 is probably less surprising, and the ribbon is more of an advanced feature.

Thanks for the contribution!
