### ISSUE TITLE
Lifting Pretty to * -> * & * -> * -> *

### ISSUE THREAD

**Issue by robrix** [quchen/prettyprinter#39]
Would you be open to a PR defining liftings of `Pretty` to * -> * and * -> * -> *, a la `Show1` &c. from `Data.Functor.Classes`? It makes (decidable) recursive instances for `Fix`, `Free`, `Cofree` &c. much easier to define:

```haskell
instance Pretty1 f => Pretty (Fix f) where
  pretty (Fix f) = liftPretty pretty prettyList f
```

If so, I’ll be happy to submit one 😊

**Comment by robrix** [comment]
For reference, here’s the implementation I’m working with currently:

https://github.com/robrix/abstract-interpretation/blob/master/src/Data/Functor/Classes/Pretty.hs

(I’d document everything before submission, of course.)

**Comment by quchen** [comment]
Hm, the code doesn’t really look very nice, but since we now have Show1 etc. in Base, I think this is something we could include. I’d like to keep it minimally invasive though – from a Haddock standpoint, there shouldn’t be too many new exports, the (single exposed main) module is long enough as it is.

Can you explain why `Pretty1Of` is necessary a bit? I’m familiar with `Show1`, but not with `Show1Of`.

**Comment by robrix** [comment]
> Hm, the code doesn’t really look very nice, but since we now have Show1 etc. in Base, I think this is something we could include. I’d like to keep it minimally invasive though – from a Haddock standpoint, there shouldn’t be too many new exports, the (single exposed main) module is long enough as it is.

Okay, you bet 👍

Would you be interested in including a generically-derivable implementation of `Pretty1`? This really isn’t make-or-break for me; we can always include it in our project and replace `deriving Pretty1` with `instance Pretty1 F where liftPretty = genericLiftPretty`.

I’m guessing not given the above, but wanted to double-check since it wouldn’t necessarily have to increase the API’s surface area.

> Can you explain why `Pretty1Of` is necessary a bit? I’m familiar with `Show1`, but not with `Show1Of`.

Oh, my bad—I don’t think we should include it at all. It’s a convenience to give you a `Pretty` instance if you have a `Pretty1` instance, and helps to avoid orphan instances. I see little benefit to including it here, because presumably we’d just write the `Pretty` instance in the first place.

**Comment by quchen** [comment]
I don’t think Pretty1 should be derivable (likewise for Pretty), since prettiness is not something that follows any laws. If push comes to shove and we really need a quick Pretty instance, there is `prettyViaShow`.

**Comment by quchen** [comment]
I’m closing this issue since the corresponding PR (#40) looks good enough to subsume it.
