### ISSUE TITLE
"atLeastAlign" (or should tupled etc *not* align)?

### ISSUE THREAD

**Issue by ocharles** [quchen/prettyprinter#41]
I have a problem at the moment with the interaction between `hang` and `align`. Fundamentally, the problem is that `tupled` calls `align` internally, but `align` can undo the indentation caused by `hang`. Consider the following:

```
λ> tupled ["aaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaa"]
( aaaaaaaaaaaaaaaaaaaa
, aaaaaaaaaaaaaaaaaa )
λ> hang 2 $ tupled ["aaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaa"]
( aaaaaaaaaaaaaaaaaaaa
, aaaaaaaaaaaaaaaaaa )
```

As we can see, `tupled` is not respecting the hanging. Options:

1. Introduce `atLeastAlign`, which tries to align, but never decreases indentation.
2. `encloseSep` should not call `align`.

**Comment by quchen** [comment]
You’re right, `hang` increases the indentation level, while `align` will set it to the current position again, undoing the `hang`. I don’t think changing `encloseSep` is a good solution because it breaks compatibility, but a form of `atLeastAlign` is easily defined via

```haskell
atLeatAlign d = column (\k -> nesting (\i -> nest (max 0 (k - i)) d))
-- for comparison
align d       = column (\k -> nesting (\i -> nest        (k - i)  d))
```

That should solve your issue on a user level. The question now is whether this is important enough to be added to the library.

**Comment by ocharles** [comment]
Yea, I have that `atLeastAlign` locally, along with redefinitions of `encloseSep` and things that use it.

**Comment by quchen** [comment]
I think I’ll remove the `align` from `encloseSep`, but since that’s a breaking change it’ll take some time to reach Hackage. Reasons include that »enclosed and separated« does not hint at alignment, and combining it with `align`ment seems natural to do when this is desired.

**Comment by quchen** [comment]
Done! Thanks for the suggestion/feedback, I think it’s a bit more verbose right now (since the standard use case is `align`ing), but the user code is probably easier to read with the explicit call, and the more fine-grained control over indentation drives the point home.

**Comment by ocharles** [comment]
I'm on board with this, thanks!
