### ISSUE TITLE
prettyprinter-ansi-terminal: There should be a way to reset a color/style to terminal default

### ISSUE THREAD

**Issue by fmthoma** [quchen/prettyprinter#42]
Currently, it's possible to keep some colors and override others (e.g. keep foreground color, but change background color), but it's impossible to revert to terminal default for one or the other. This is particularly inconvenient when trying to use a »default« color like black or white in a color scheme that is required to work for both dark and light backgrounds.

This behavior is encoded in the type `AnsiStyle`:

```haskell
data AnsiStyle = SetAnsiStyle
    { ansiForeground  :: Maybe (Intensity, Color) -- ^ Set the foreground color, or keep the old one.
    , ansiBackground  :: Maybe (Intensity, Color) -- ^ Set the background color, or keep the old one.
    , ansiBold        :: Maybe Bold               -- ^ Switch on boldness, or don’t do anything.
    , ansiItalics     :: Maybe Italicized         -- ^ Switch on italics, or don’t do anything.
    , ansiUnderlining :: Maybe Underlined         -- ^ Switch on underlining, or don’t do anything.
    } deriving (Eq, Ord, Show)
```

Instead of `Maybe a`, this should be a ternary `Keep | Default | SetTo a` just like `vty`'s [`Attr`](https://github.com/jtdaugherty/vty/blob/4f5e7422df9f9590c788bf90c6f5832d7d7fd580/src/Graphics/Vty/Attributes.hs#L76) does it with its [`MaybeDefault`](https://github.com/jtdaugherty/vty/blob/4f5e7422df9f9590c788bf90c6f5832d7d7fd580/src/Graphics/Vty/Attributes.hs#L136) type.

**Comment by quchen** [comment]
Makes sense!

**Comment by fmthoma** [comment]
Actually, I just realized that due to the design of the prettyprinter, this is not even necessary: The behaivor is actually to [reset](https://github.com/quchen/prettyprinter/blob/c68ede23432e2b5210d91d9c6287e3d9247af472/prettyprinter-ansi-terminal/src/Data/Text/Prettyprint/Doc/Render/Terminal/Internal.hs#L278) any style before applying the new style, so `mempty` is already the default style.

So it's really the converse that's missing, the possibility to keep a style from the previous annotation. Which is probably not even desirable, as it drags around context we probably don't want to have most of the time.

So the real issue I just had is with documentation:

> `ansiForeground  :: Maybe (Intensity, Color) -- ^ Set the foreground color, or keep the old one.`

really should be »[…] or keep the default one«.

**Comment by quchen** [comment]
»Or keep the old one (or the default if there was none)« sounds a bit verbose though, no?

**Comment by fmthoma** [comment]
The fact that `blue <> red == blue` also somehow contradicts the »set the foreground color« part – adding `red` on top of `blue` does not set the color to `red`, it will stay blue.

**Comment by fmthoma** [comment]
The terminology of »keeping« and »setting« a color lives on two different levels: The level of `AnsiStyle`'s `Semigroup` instance (where `mempty` keeps whatever was set previously or after), and the level of styling a `Doc` (where `mempty` actually reverts everything to default).

**Comment by quchen** [comment]
Closing since we resolved this by talking about it, or am I mistaken?

**Comment by banacorn** [comment]
I think the documentation could be rephrased better, perhaps with the word **"reset"** mentioned somewhere.
