### ISSUE TITLE
Pretty instance for Data.Scientific

### ISSUE THREAD

**Issue by PierreR** [quchen/prettyprinter#47]
Would you be open to add a Pretty instance for `Data.Scientific` ?

It can easily be added by users at the expense of an orphan instance and the use of the default implementation of `pretty`  or the internal `unsafeViaShow`.

I can make a PR but I guess you might have concerns about the added dependency.

**Comment by quchen** [comment]
I don’t want an additional dependency simply to have more instances available, this would open the doors to depending on half of Hackage. However, I’m not sure why `(unsafe)ViaShow` is not exposed in the public module – their point is precisely making writing instances easier! So if you want to make those public, feel free to submit a PR.

**Comment by quchen** [comment]
Opened #48 for this particular solution. Thanks for the (future) pull request!
