### ISSUE TITLE
The documentation mentions functions colorDull, bgColor, and bgColorDull, but they are nowhere to be found.

### ISSUE THREAD

**Issue by kindaro** [quchen/prettyprinter#52]
Or maybe my grep is broken.

```
% grep -r bgColor .
./app/GenerateReadme.hs:          have been combined in /color/ /colorDull/, /bgColor/, and
./app/GenerateReadme.hs:          /bgColorDull/ functions. |]
./src/Data/Text/Prettyprint/Doc.hs:--     'colorDull', 'bgColor', and 'bgColorDull' functions.
./README.md:     /colorDull/, /bgColor/, and /bgColorDull/ functions.
% grep '^version' *.cabal
version:             1.2.0.1
```

**Comment by quchen** [comment]
It’s there as part of the prettyprinter-ansi-terminal package, https://github.com/quchen/prettyprinter/blob/master/prettyprinter-ansi-terminal/src/Data/Text/Prettyprint/Doc/Render/Terminal/Internal.hs#L62

How did you come across this issue? Is it maybe just a bug in my Haddock comments somewhere?

**Comment by kindaro** [comment]
The terminal excerpt I posted is the result of running something along the lines of:

```
% stack unpack prettyprinter
% cd prettyprinter-1.2.0.1
% grep -r bgColor .
```
It was me trying to find this function somewhere in the code of `prettyprinter`.

You can search for e.g. `bgColor` in the docs for `prettyprinter` [on Hackage](https://hackage.haskell.org/package/prettyprinter-1.2.0.1/docs/Data-Text-Prettyprint-Doc.html). In particular, in Data.Text.Prettyprint.Doc, section "Migration guide":

> Instead of providing an own colorization function for each color/intensity/layer combination, they have been combined in color, colorDull, bgColor, and bgColorDull functions.

There is no mention of `prettyprinter-ansi-terminal` package, so I did not even suspect its existence.

**Comment by quchen** [comment]
I see, in that case it’s indeed a documentation bug!

**Comment by quchen** [comment]
Alright, I’ve added a few words to the documentation, it should be clearer now. Thanks for your report!
