### ISSUE TITLE
right align?

### ISSUE THREAD

**Issue by jchia** [quchen/prettyprinter#55]
`align` implicitly uses left padding. Is there a way to do right padding instead? I don't see any way. Can this be added a a feature?

**Comment by quchen** [comment]
I don’t know how that would be done, since the layout algorithm assumes writing left-to-right, introducing line breaks if things don’t fit the current layout constraints.

**Comment by ad-si** [comment]
Can you explain this in more detail? Feels like it's an essential feature and I'm really missing it 😕

**Comment by quchen** [comment]
The problem here is the `show` – this assumes a specific layout (`show` uses `defaultLayoutOptions`) in order to create a document (that is then laid out again to convert it to output). This solution breaks if you want to have a document rendered 80 characters wide for example – the width of the `show`n document is potentially much larger than that, because it assumes unbounded width.

**Comment by ad-si** [comment]
I see, and something more bare bones like this?

```haskell
leftFill :: Int -> Text -> Doc ann
leftFill width doc =
  let numSpaces = width - (T.length doc)
  in (P.fold $ P.replicate numSpaces space) <> doc
```

**Comment by quchen** [comment]
That’s reimplementing [justification already provided in the Text API](http://hackage.haskell.org/package/text-1.2.3.0/docs/Data-Text.html#g:10). Left-filling inside a `Doc` should not be specific to plain `Text`, but apply to any enclosed `Doc` and do the right thing. You can implement special workarounds for specific use cases, but I don’t see a *general* way of having this in the library in its current form (unfortunately).

**Comment by ad-si** [comment]
Ok, I guess `justifyRight` would be the right thing in my case.
I think a few functions for specific cases wouldn't be to bad either until someone can come up with something more generic, but I don't have a specific example right now anyways.
So feel free to close this issue.
