### ISSUE TITLE
Delay printing broken lines

### ISSUE THREAD

**Issue by ag-eitilt** [quchen/prettyprinter#68]
I've nearly gotten columns working on my particular (rather simple -- just parallel `[Text]`s) use case, in *two* different ways, but I can't find any way to get the last step of either of them.

The first is by stacking the `Text` in a `vcat` and then gluing those horizontally (it still needs an `align`, but that probably wouldn't be too difficult to add).  It currently just cascades downward, though, and reading through some of the requests, it sounds like a reverse newline isn't really doable.  Besides, that seems like a recipe for horrible output compatibility with anything but terminal emulators, so I've pretty much abandoned that code path.

The second, which seems much more promising, is padding the raw `Text`s myself ahead of time and just letting the standard layout go ahead dumbly.  This is actually working remarkably well, and I have everything lined up where I want it -- horizontally.  If the lines exceed the ribbon, they wrap as normal so I get `112233` rather than `123123`.  I can handle the collation myself easily enough, if I only had a way of getting back the wrapped `Doc`s.

Would it be possible to add a function that, when the rendering pass collapses the laziness and we therefore know the available width, returns something like a `[Doc]` (all of the line breaks inserted) or a `(Doc, Maybe Doc)` (stops processing after the first one) that we can then manipulate before re-composing them all and passing them back up the chain?  I can't imagine the algorithm requires the second line to be printed to know the width of the first, but I'm not sure if there's some hidden incompatability lying in one of the output formats I'm not thinking of.  Or is there already something like that I'm just not seeing?

EDIT: Or, alternatively, a way of providing a `Doc -> Doc` function which could perform some arbitrary modification on the second line before passing it (or in this case, something else) back to the layout engine?  This would perhaps be the best way of doing so, as it wouldn't require any escape hatches once the layout code was entered, but I haven't looked at the internals enough to know whether the types at that point would allow for it; I'd imagine so because the algorithm doesn't provide any lookahead, but you could have split things into multiple stages, and by the time the line breaks are inserted, there's a possibility the `Doc`s have been rendered into an intermediate datatype.

**Comment by quchen** [comment]
The WL algorithm has no knowledge of data already handled; it just knows where it is, and what’s to come. This is the main reason multi-column layouts are impossible (without significantly altering the algorithm).
