### ISSUE TITLE
Migrate Idris to the new prettyprinter *as a test*

### ISSUE THREAD

**Issue by quchen** [quchen/prettyprinter#7]
Idris is one of the biggest publich projects using a Wadler/Leijen prettyprinter. Because of that, it’s an excellent playground for testing how much effort it takes to migrate it to the present library, and to figure out what might break.

**Comment by minad** [comment]
@davdar and @david-christiansen is also working on https://github.com/davdar/final-pretty-printer. Would be interesting to know what @david-christiansen's plans are...

**Comment by david-christiansen** [comment]
I plan to port Idris to the Final Pretty Printer. Indeed, work is already underway.

**Comment by minad** [comment]
@david-christiansen Cool, what is this final pretty printer about? Is there a paper or a reference? I've seen it is monadic.

**Comment by quchen** [comment]
Porting Idris is trivial (around 30 minutes work including everything), apart from two display tests that fail. I haven’t been able to fix those yet; it’s a matter of a newline being in the wrong place.

**Comment by david-christiansen** [comment]
@minad It's an extensible pretty printer library. We're submitting a paper to the Haskell Symposium this year, a draft will be out soon and there will be a Hackage release. In addition to extensibility, it also supports proportional-width fonts and annotations. More to come.

**Comment by david-christiansen** [comment]
Wow, this library looks really nice!
