### ISSUE TITLE
Single space between horizontally separated empty and non-empty Docs?

### ISSUE THREAD

**Issue by owi-symbiont** [quchen/prettyprinter#70]
Hi!

First, thank you for the nice library, David! I have a question that I think is related to https://github.com/quchen/prettyprinter/issues/56, and perhaps even a duplicate, but anyway:

Is there a way to use `<+>`/`sep`/`hsep` with empty `Doc`s such that you only get a single space in between non-empty documents? I get multiple spaces when separating empty docs, as seen in the following example:

```haskell
{-# LANGUAGE OverloadedStrings #-}
import           Data.Text.Prettyprint.Doc
import           Data.Text.Prettyprint.Doc.Render.Text

main :: IO ()
main = do
  putDoc ("foo" <+> hsep [mempty, "bar"])
  putStrLn ""
  putDoc ("foo" <+> mempty <+> "bar")
  putStrLn ""
  putDoc (hsep ["foo", mempty, "bar"])
```

Output (note the double spaces between words):

```
$ cabal v2-run
...
foo  bar
foo  bar
foo  bar
```

As you noted in #56, a solution is to manually filter out empty items before converting them to `Doc`s, e.g. a rendering function `[MyThing] -> [Maybe Doc]` and then doing `sep . mapMaybe`. But if there's any support for this in the library I'd rather use that.

Thanks!

**Comment by quchen** [comment]
My advice woiuld be to defer putting data into `Doc` as long as possible, in order to avoid adding empty documents that you don’t want in the first place. Cleaning unclean `Doc` in retrospect is not something I recommend.

Unfortunately, this very issue you’re mentioning is the main blocker for using `prettyprinter` for GHC itself :-|

**Comment by owi-symbiont** [comment]
Gotcha. It's fine in my case, just wanted to double check. Thank you! Feel free to close this ticket, by the way.
