### ISSUE TITLE
removeTrailingWhitespace erroneously removes empty lines

### ISSUE THREAD

**Issue by peti** [quchen/prettyprinter#71]
~~~ haskell
import Data.Text.Prettyprint.Doc
import Data.Text.Prettyprint.Doc.Render.String

doc :: Doc ann
doc = mconcat [ pretty "paragraph 1", hardline, hardline, pretty "paragraph 2" ]

good :: IO ()
good = putStrLn $ renderString . layoutPretty defaultLayoutOptions $ doc

bad :: IO ()
bad = putStrLn $ renderString . removeTrailingWhitespace . layoutPretty defaultLayoutOptions $ doc
~~~

The first version produces the output I want:

~~~
λ> good
paragraph 1

paragraph 2
~~~

But the second version -- the one that includes `removeTrailingWhitespace` -- loses the empty line that's supposed to separate the paragraphs:

~~~
λ> bad
paragraph 1
paragraph 2
~~~

Is this intended behavior? Or am I doing something wrong?

**Comment by quchen** [comment]
Had to add another commit 9ea5da0a4cd05cdbddcc98a8edd62f4d0bb45219 to fix the rest of the testsuite. Premature push :-x
