### ISSUE TITLE
Feature Request: Support `prettyPrec` function

### ISSUE THREAD

**Issue by Ailrun** [quchen/prettyprinter#76]
I tried to pretty print my small language, but I found that it is really hard without a precedence for printing.

Is there a reason for not supporting `prettyPrec` class method like the following? If there is, could you let me know? Is it bad for performance or any other problem?
```haskell
prettyPrec :: Int -> a -> Doc ann 
```

If it is possible, I'm willing to send a PR for it.

**Comment by quchen** [comment]
Prettyprinter is a general-purpose layouting engine, and precedence handling is something only relevant to a special notation of mathematical applications (namely: omitting parentheses). I don’t think `prettyPrec` is a good fit for that reason.

But fear not! Have you considered annotating expressions with precedence? I think you should be able to write your own renderer (i.e. a `SimpleDoc -> YourOutputType` function) that respects the annotations and puts parentheses only where needed.

**Comment by Ailrun** [comment]
@quchen OK, so I need to implement my new renderer to achieve what I want with `prettyprinter`, right?
Thank you for your answer, and I will try the way you recommend.

**Comment by quchen** [comment]
Yes.

The simplest pre-defined renderers are the ones you’re probably already using. [(link)](http://hackage.haskell.org/package/prettyprinter-1.3.0/docs/Data-Text-Prettyprint-Doc-Render-Text.html)

In the prettyprinter-ansi-terminal package, you’ll find a more complicated renderer for ANSI terminal styled text. [(link)](http://hackage.haskell.org/package/prettyprinter-ansi-terminal-1.1.1.2/docs/Data-Text-Prettyprint-Doc-Render-Terminal.html)

**Comment by Ailrun** [comment]
@quchen I notice that I cannot use `Pretty` class too, if I want to annotate my `Doc`.
Am I missing something? Or I should add my own type class to do something like this?

**Comment by Ailrun** [comment]
@quchen Thank you for your additional comment, I think adding new class like
```haskell
class PrettyPrec a where
  prettyPrec :: Int -> a -> Doc ann

instance Pretty a => PrettyPrec a where
  prettyPrec _ = pretty
```
would be a best option for me.
I close this issue now, and if there is any related problem, I will reopen then.

Thank you again for your great help!
