### ISSUE TITLE
Can't install with recent ghc ?

### ISSUE THREAD

**Issue by gameboo** [quchen/prettyprinter#77]
**EDIT**: my bad, looks like it was due to my cabal version, which was probably a not stable one (cabal-install-3.0). Downgrading to 2.4.1.0 did the trick.

Hi there,

I am not sure I am reading the situation correctly, but I believe I am having issues installing package for toolchain version reasons (maybe?).

```
$ cabal install --lib prettyprinter
Resolving dependencies...
Build profile: -w ghc-8.6.3 -O1
In order, the following will be built (use -v for more details):
 - prettyprinter-1.3.0 (lib) (requires download & build)
Downloading  prettyprinter-1.3.0
Downloaded   prettyprinter-1.3.0
Starting     prettyprinter-1.3.0 (lib)
Building     prettyprinter-1.3.0 (lib)
Installing   prettyprinter-1.3.0 (lib)
Completed    prettyprinter-1.3.0 (lib)
Distribution/Simple/GHC.hs:1959:5-56: Irrefutable pattern failed for pattern Just ghcPkgProg
```
This also happened to me with `ghc-8.6.5`...

Am I missing a step somewhere? If it is indeed not expected that the lib works with a recent compiler and I depend on a recent version of the compiler for the project I work on, is using the library just not an option (or would it be a trivial update)?

Thanks.

**Comment by quchen** [comment]
Glad the issue resolved itself, that would have been quite a tough bug to catch, since my local and remote (Travis) builds all run smoothly.

That said, I do not have any CI that uses Cabal, so maybe I should add that at some point. That would mean I needed to re-familiarize myself with Cabal again though.
