### ISSUE TITLE
“Nest” behavior unexpected

### ISSUE THREAD

**Issue by jtdaugherty** [quchen/prettyprinter#78]
I am using `prettyprinter` version `1.3.0`. The following program behaves unexpectedly for me:
```haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Data.Text.Prettyprint.Doc
import Data.Text.Prettyprint.Doc.Render.String

main :: IO ()          
main = do
    let st = layoutPretty defaultLayoutOptions v
        v = vcat [ nest 4 "Foobar"
                 , nest 8 "Blah"
                 ]
    putStrLn $ renderString st
```

In particular, I expect the output to be rendered with the desired amount of indentation:
```
    Foobar
        Blah
```
But instead I get:
```
Foobar
Blah
```
The presence of `vcat` does not have an effect. Even attempting to print just `nest 4 “Foobar”` has the same unexpected result. What am I missing?

**Comment by quchen** [comment]
This is the expected beahvior. [`nest`][nest] increases the internal indentation level, which only has an effect after a newline (within the nest) has been encountered, e.g.

```haskell
nest 4 (vcat ["Lorem", "Ipsum"])

-- Lorem
-- ␣␣␣␣Ipsum
```

What you’re looking for is [`indent`][indent],

```haskell
vcat [indent 4 "Lorem", indent 8 "Ipsum"]

-- ␣␣␣␣Lorem
-- ␣␣␣␣␣␣␣␣Ipsum
```

You may also want to have a look at [`hang`][hang].

[hang]: https://hackage.haskell.org/package/prettyprinter-1.3.0/docs/Data-Text-Prettyprint-Doc.html#v:hang
[indent]: https://hackage.haskell.org/package/prettyprinter-1.3.0/docs/Data-Text-Prettyprint-Doc.html#v:indent
[nest]: https://hackage.haskell.org/package/prettyprinter-1.3.0/docs/Data-Text-Prettyprint-Doc.html#v:nest

**Comment by jtdaugherty** [comment]
Okay, thanks for the clarification. Looking at the documentation (and your comment), it seems to me that it should be safe to read "current indentation level" as implicitly zero if no nesting has been done, so I think it's really surprising that a newline has to be introduced. I ran into this exactly because my program used `nest` and got wildly different and surprising results depending on context. In some cases using `nest` got me the behavior I wanted, and in some it did not, so going forward I will probably always use `indent` instead of `nest`.

Even if this is the expected behavior, I think the documentation could make the difference between `nest` and `indent` clearer. Indent says
```
indents document x with i spaces, starting from the current cursor position.
```
and `nest` says
```
lays out the document x with the current indentation level increased by i.
```
and those read like the same thing to me.

**Comment by quchen** [comment]
I agree the documentation should be clearer here! Any suggestions? Otherwise I’ll just make something up. :-)

**Comment by quchen** [comment]
Better?

**Comment by jtdaugherty** [comment]
Thank you very much - that does help! I think the new docs help even more than your comment here - "indentation of the following lines" was the salient bit that helped me understand the difference. I think it could be even clearer as something like "indentation of all lines after the first one."

**Comment by jtdaugherty** [comment]
As far as the difference goes, this has me wondering: it seems that `nest` and `indent` are close enough to each other that I'm wondering why `nest` exists at all, since (assuming I understand correctly)
```
vcat [x, indent i xs]
```
is the same as
```
nest i (vcat $ x:xs)
```

**Comment by quchen** [comment]
You’re right, `nest` might not be the best API function, since what users want is usually `indent` or `hang`. However, `nest` is actually one of the primitives (constructor of `Doc`) with a lot of other functions (such as `indent` and `hang`, actually) built with it, and it’s also the most performant of the bunch, since it does no computation and can easily be analyzed from within the program, which the others cannot (since they contain callbacks that aren’t known statically).

**Comment by jtdaugherty** [comment]
Okay, thanks for the explanation.
