### ISSUE TITLE
A diagnostic representation for "Doc"

### ISSUE THREAD

**Issue by sjakobi** [quchen/prettyprinter#90]
I often want to see the internal structure of a `Doc`. I can use the derived `Show` instance in my fork for this, but I would prefer something more conveniently available.

**Comment by sjakobi** [comment]
If the existing `Show` instance for `Doc` should continue to pretty-print the document, how about a "clone" of `Doc` with the same constructors. I.e.

```
data Diag ann =
    Fail
    | Empty
    | Char !Char
    ...
deriving instance Show (Int -> Diag ann) => Show (Diag ann)
```

```
diag :: (Show ann, Show (Int -> Diag ann)) => Doc ann -> String
diag = show . docToDiag
```

Could be nicer, but would already be _very_ useful!

**Comment by quchen** [comment]
How would this deal with function-based constructors like `Column`? I like the idea though, and this would make a good addition to the `Internal` module.

**Comment by sjakobi** [comment]
> How would this deal with function-based constructors like `Column`?

Users that import `Text.Show.Functions` from `base` would see

    Column <function>

That's not great, but better than nothing.

I guess we could also "scan" or "sample" these functions – this could even be configurable!

**Comment by quchen** [comment]
Or we could render the Doc as a Doc, and use the nesting/indentation of the rendering to put into the function fields. Or would that be circular?

**Comment by sjakobi** [comment]
Since the diagnostic representation should be particularly useful when working on prettyprinter itself, I think it's better not to rely on it for this purpose.
